# Generated by Django 2.1.5 on 2019-02-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0003_auto_20190212_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-uploaded_at',)},
        ),
    ]
