# Generated by Django 2.1.5 on 2019-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0004_auto_20190214_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
