# Generated by Django 2.1.5 on 2019-03-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0005_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
