# Generated by Django 2.1.5 on 2019-03-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0006_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(default='media/photos/No_Image_Available.jpg', upload_to='photos/'),
        ),
    ]
