# Generated by Django 2.1.5 on 2019-03-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0011_auto_20190328_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/No_Image_Available.jpg', upload_to='photos/'),
        ),
    ]
