# Generated by Django 2.1.5 on 2019-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0012_auto_20190328_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/NoImage.jpg', upload_to='photos/'),
        ),
    ]
