# Generated by Django 2.1.5 on 2019-03-28 08:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0013_auto_20190328_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/NoImage.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\chirag.soni\\olxApp\\media'), upload_to='photos/'),
        ),
    ]
