# Generated by Django 2.1.5 on 2019-03-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0014_auto_20190328_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/NoImage.jpg', upload_to='photos/'),
        ),
    ]
