# Generated by Django 2.1.5 on 2019-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0019_remove_photo_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField(default=0)),
                ('photo_type', models.CharField(db_index=True, max_length=70)),
                ('file', models.FileField(default='NoImage.jpg', upload_to='photos/')),
                ('cover_photo_flag', models.CharField(db_index=True, default=0, max_length=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
