# Generated by Django 2.1.5 on 2019-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0022_product_uploaded_by_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='mark_as_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
